name: C Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target website URL to test'
        required: true
        default: 'https://example.com'
        type: string

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libnghttp2-dev

      - name: Build program
        run: gcc src/main.c -o main

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run script
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Running with custom URL: ${{ github.event.inputs.target_url }}"
            ./run.sh "${{ github.event.inputs.target_url }}"
          else
            echo "Running with default URL"
            ./run.sh "https://example.com"
          fi

      - name: Display result
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Script execution completed for URL: ${{ github.event.inputs.target_url }}"
          else
            echo "Script execution completed for URL: https://example.com"
          fi
